version: "3.4"
services:
  webapp:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=qweijowqknqwke
      - DATABASE_URL=psql://test:test@dbtodo:5432/test
      - DEBUG=True
    depends_on:
      - dbtodo
    links:
      - dbtodo:dbtodo
    command: sh init.sh
  dbtodo:
    image: postgres:12
    container_name: dbtodo
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

