version: "3.4"
services:
  webapp:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY
      - DATABASE_URL
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db:db
    command: ['sh', '/webapp/init.sh']
  db:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data
    container_name: dbtodo
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  pg-data:
    driver: local