# Generated by Django 4.0.3 on 2022-04-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
