# Generated by Django 4.0.3 on 2022-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userapp_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
