# Generated by Django 4.0.3 on 2022-04-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_userapp_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
